---
services:
  # Base container is used for development tasks like tests, linting,
  # and building docs.
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        userid: ${USE_UID:-10001}
        groupid: ${USE_GID:-10001}
    image: eliot:build
    env_file:
      - docker/config/local_dev.env
      - .env

  # Symbolicator service
  eliot:
    extends:
      service: base
    ports:
      - "${EXPOSE_ELIOT_PORT:-8000}:8000"
    depends_on:
      - fakesentry
      - statsd
    links:
      - fakesentry
      - statsd
    command: ["eliot"]

  # Container specifically for running tests.
  test:
    extends:
      service: base
    env_file:
      - docker/config/local_dev.env
      - docker/config/test.env
    links:
      - fakesentry
      - statsd

  devcontainer:
    extends:
      service: test
    build:
      dockerfile: .devcontainer/Dockerfile
      args:
        userid: ${USE_UID:-10001}
        groupid: ${USE_GID:-10001}
    image: eliot-devcontainer
    entrypoint: ["sleep", "inf"]
    stop_signal: SIGKILL  # Doesn't seem to respond to anything else
    volumes:
      - $PWD:/app

  # https://github.com/willkg/kent
  fakesentry:
    build:
      context: docker/images/fakesentry
    image: local/eliot_fakesentry
    ports:
      - "${EXPOSE_SENTRY_PORT:-8090}:8090"
    command: run --host 0.0.0.0 --port 8090
    stop_signal: SIGINT

  # https://hub.docker.com/r/hopsoft/graphite-statsd/
  statsd:
    image: hopsoft/graphite-statsd:latest
    ports:
      - "${EXPOSE_GRAFANA_PORT:-8081}:80"
